### ISSUE TITLE
大神可以给个open-codes下载链接吗

### ISSUE THREAD

**Issue by txyyh** [neatgz/PotPlayer_OneKey_Tool#1]
本人常用，但苦于无处下载新版的open-codes，纯小白，自己找不出，谢谢！

**Comment by suryhp** [comment]
https://t1.daumcdn.net/potplayer/PotPlayer/Codec/OpenCodecSetup.exe
https://t1.daumcdn.net/potplayer/PotPlayer/Codec/OpenCodecSetup64.exe

**Comment by txyyh** [comment]
十分感谢！

**Comment by dreamyounger** [comment]
谢谢！
